package tinybot:plugin@0.1.0;

interface types {
    record message-content {
        text: string,
    }

    record action {
        finish: bool,
        reply: option<message-content>,
    }

    record message {
        target-type: string,
        target: string,
        content: message-content,
    }

    variant bot-event {
        message(message),
    }
}

interface plugin-api {
    use types.{action, bot-event};

    active: func(evt: bot-event) -> bool;
    handle: func(evt: bot-event) -> action;
}

world tinybot-plugin {
    export plugin-api;
}
